### ISSUE TITLE
Address Milestone 1 Feedback (4.2.3 Test Cases)

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#101]
Adress the following feedback for the milestone 1 documentation:
You could do many more test cases: what if the user does not provide all the required information? What should happen? Does this happen? What if the user does not click the sign in button? What if the sign in is not successful? Could it be unsuccessful for different reasons requiring different reactions from the system? Which each would have to be tested. This is just one example, for the other tests you can also generate many more cases.
Recommended Priority: 7
Recommended Difficulty: 5

**Comment by print-Eruki** [comment]
Added more three more test cases into the documentation
