### ISSUE TITLE
[Lecture Topic Task] Functional Testing of review feature

### ISSUE THREAD

**Issue by Jaime2424** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#105]
As specified in the UPRMarketplace documentation, perform test cases: 
- TC001
- TC002
- TC003
- TC004 
Urgency: 5/5
Difficulty: 4/5

**Comment by JeremyCaban** [comment]
Test cases TC001, TC002, TC003, and TC004 have been performed and the successes and failures have been documented accordingly.
