### ISSUE TITLE
Address Milestone 2 Feedback : Epics

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#128]
Address the following feedback for the milestone 2 documentation:

Recommended Difficulty: 1
Recommended Urgency: 5

**Comment by AngelGonzs** [comment]
**Feedback Received** 

>  As an epic "enhanced user experience" is not a good choice. It's okay as a high level goal or as a quality, but as an epic it's not well suited. Review what epics are: strategic objectives at a higher level than user stories. I don't see how enhancing user experience fit into this. If you want to consult resources online, search for "epic theme user story software development".

**Comment by eternero** [comment]
Feedback for Epics has been addressed and added to the documentation. Task can be reviewed and closed.
