### ISSUE TITLE
Address Milestone 2 Feedback Improve requirements

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#130]
Address the following feedback for the milestone 2 documentation:

Recommended Difficulty: 
Recommended Urgency:

**Comment by YeranConcepcion** [comment]
I've said this many times: requirements need to require! That means they need to be worded in a certain way. "Shall allow" is not strong enough: an adversary developer could not do anything, then just claim they are satisfying the requirement arguing that they are not forbidding e.g. students to register and that therefore they are allowing it and that therefore they are satisfying the requirement. This is just too passive. What you might want to say is that your system-to-be shall provide the means for users to register.

**Comment by JeremyCaban** [comment]
Addressed feedback for the requirements section of the documentation.
