### ISSUE TITLE
[Lecture Topic Task] Edit SignUp and Forgotten Password

### ISSUE THREAD

**Issue by JuanJRivera** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#145]
SignUp must store a user's phone number and provide them a security question.

Forgotten Password must only let you reset your password after you've introduced your personal information including the security question.

Test Forgotten Password thoroughly and implement AB testing.

**Comment by warm007** [comment]
<img width="131" alt="FORGOT PASS FORM" src="https://github.com/uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace/assets/112134756/3c0fd6ca-bceb-436c-af3a-e0fc739bbfb5">

**Comment by MarkoSchuetz** [comment]
Ah, removed it from the wrong board...
