### ISSUE TITLE
[Lecture Topic Task] Test Login and Sign Up Function (AB Testing)

### ISSUE THREAD

**Issue by JuanJRivera** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#16]
Test Login and Sign Up pages function thoroughly and implement AB testing.

**Comment by YeranConcepcion** [comment]
I can work on this

**Comment by warm007** [comment]
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace/assets/112134756/7c49db8c-e146-4f54-8b7d-2a98869d0f04)

**Comment by warm007** [comment]
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace/assets/112134756/0ce1d280-5aac-4ee8-a850-fbe86a5c7bda)

**Comment by warm007** [comment]
Added to the documentation!
