### ISSUE TITLE
Interface Requirements, Machine Requirements

### ISSUE THREAD

**Issue by Alex202-0** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#25]
Add the Interface Requirements, Machine Requirements section to the documentation and add the relevant information to it.

Requirements for completion: Developed idea of the Interface Requirements, Machine Requirements section in the Project Document.

Urgency: 5
Difficulty: 4

**Comment by YeranConcepcion** [comment]
***From @JuanJRivera 
**Inclusion of Personas in Documentation:** 

- **Purpose**: Personas are essential tools in justifying user stories, features, epics, and requirements for a project. They serve as a foundation for understanding the user's needs and preferences.

- **Development Process**:
  1. **Starting Point**: Begin by considering yourself (assuming you are a potential user), along with friends, family, peers, and anyone who might benefit from your software.
  2. **Common Traits Identification**: Determine what these individuals have in common. This involves a deep understanding of their needs, behaviors, and preferences.
  3. **Creation of 'Frankensteins'**: Combine these common traits to create imaginary personas. These are fictional characters but with realistic and plausible traits.
  4. **Characterization**: Give each persona distinct traits that are easily memorable. This helps in quick identification and recall by the team members.

- **Objective**:
  - **Memorability and Utility**: The collection of traits in each persona should be easy to remember. The idea is that mentioning the name of a persona should immediately evoke their traits in everyone’s mind, ensuring that the team has a shared understanding of the user types they are designing for.
  
  
 - Urgency: P0 (5 pts)
 - Difficulty: 2/5
 - Total: 10 pts

**Comment by AngelGonzs** [comment]
Work has been completed, issue can be closed upon review.

**Comment by sandy-marrero** [comment]
Interface Requirements are inaccurate and not at all relevant to our project, issue is reopened, and tasks points are now moved to Milestone 2.
