### ISSUE TITLE
Create Login/Sign Up Section Mockups

### ISSUE THREAD

**Issue by JeremyCaban** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#38]
Add the Risk Identification section to the documentation and add the relevant information to it.

Requirements for completion: Developed idea of the Risk Identification section in the Project Document.

Urgency: 5
Difficulty 4

**Comment by warm007** [comment]
**UPRM Marketplace Login/Sign Up Section Mockups (Documentation)**

**Login Section**

1. Visual Theme

•	Color Scheme: Utilize green and white as the primary colors to align with the University of Puerto Rico at Mayagüez (UPRM) branding.
•	Layout: A centered login form on the page, featuring the UPRM logo prominently at the top, followed by a welcoming message: "Welcome to the UPRM Marketplace. Please log in to continue."

2. Fields

•	Email Address: Input field with placeholder "Enter your UPRM email address", enforcing validation for "@upr.edu" domain emails. Display an error message "Please use your UPRM email address" for invalid inputs.
•	Password: Secure field with input masking and a placeholder "Enter your password". Include a visibility toggle for user convenience.

3. Features
•	Forgot Password?: A subtly styled link for users to reset their password if needed.
•	Log In Button: Prominently displayed with the label "Log In".



**Sign Up Section**

1. Visual Theme

•	Color Scheme and Branding: Match the login section with green and white colors and incorporate the UPRM logo.
•	Layout: Similar to the login section but includes additional fields for account creation. Begin with the UPRM logo and the message: "Join the UPRM Marketplace Community."

2.Fields

•	Full Name: Input field labeled "Full Name", with placeholder "Enter your full name here".
•	Email Address: Enforces "@upr.edu" domain with placeholder "Enter your UPRM email address". Includes domain validation with error feedback.
•	Password: Password creation field with input masking, a visibility toggle, and a placeholder "Create a password". Integrate a strength meter for real-time password strength feedback.
•	Confirm Password: Field for confirming the password with placeholder "Confirm your password", including validation to match the first password field.

3. Features
•	Sign Up Button: Clearly labeled "Sign Up" button for submitting the form.
•	Additional Information: Space to outline the benefits of joining the marketplace, emphasizing exclusive access for UPRM community members, secure transactions, and community support.

**Comment by warm007** [comment]
**Risk Identification for UPRM Marketplace**

**Objective**
This section identifies and categorizes potential risks to the project's success, aiming to proactively address factors that could impact timeline, scope, and quality.


**External Risks**
•	Market Changes: Fluctuations in market demand or competition may affect the project's relevance or viability.
•	Supply Chain Disruptions: Potential delays or disruptions in obtaining necessary hardware or services could affect project timelines.

**Internal Risks**
•	Scope Creep: Uncontrolled changes or additions to the project scope may cause delays.

**Technical Risks**
•	Integration Challenges: Difficulties in integrating new systems with existing infrastructure could cause delays.
•	Data Security: Risks of data breaches or leaks necessitate stringent security measures.


**Organizational Risks**
•	Stakeholder Alignment: Misalignment among stakeholders could lead to project delays or discontinuation.
•	Communication Breakdowns: Ineffective communication could lead to misunderstandings and errors.

**Comment by warm007** [comment]
Saludos, @sandy-marrero, @HectorSotelo! Adjunto, la documentación de "Login/Sign Up Section Mockups" y el "Risks Identification". Si alguno la puede revisar y me deja saber que les parece o si necesita que le añada algo más. Cuando nos den visto bueno, la subo al Google Doc.

**Comment by alanmercad0** [comment]
### First mock design of Log In page
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace/assets/77588911/68ab1621-4213-413a-9bc0-d9d1eab06c55)

**Comment by warm007** [comment]
<img width="457" alt="Sign Up Design OFICIAL" src="https://github.com/uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace/assets/112134756/fc772b19-e874-4777-96dc-f3f5d73053a6">
