### ISSUE TITLE
Reviews MockUp

### ISSUE THREAD

**Issue by YeranConcepcion** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#52]
Create a figma mockup of the application for the review feature component of the application. We must follow the same design established by other developers for the application. Or if not, communicate with other developers in order to create base style that will be used throughout the application, these designs must be documented as well so people can access them for future reference. 

Difficulty 4
Urgency 5

**Comment by JeremyCaban** [comment]
Mock-up for the review component has been created within the shared figma.
