### ISSUE TITLE
Reviews Feature Implementation

### ISSUE THREAD

**Issue by YeranConcepcion** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#53]
Create a functional implementation of the review feature using react native for the frontend of the application, the review feature design shall be based on the pre-established design created in Figma. At the time being, there is no need for it to be connected to the backend, but it should be able to work using mockup data, meaning that models for this data shall also be created in the front-end project of the application. 

Difficulty 5
Urgency 4

**Comment by JeremyCaban** [comment]
Developed implementation of the review page within a separate branch and merged with main.
