### ISSUE TITLE
User Stories, epics, features, Personas, Domain Requirements 

### ISSUE THREAD

**Issue by YeranConcepcion** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#54]
Add the user stories, epics, features, personas, domain requirements to the documentation document. 

Requirements for completion: Developed idea of the user stories, epics, features, personas, domain requirements.

Urgency: 5
Difficulty: 4

**Comment by AngelGonzs** [comment]
Here is the document containing Epics, User Stories and Personas:

https://docs.google.com/document/d/1uOucIUARlnBgG8LbpRqFA03dCfcyEmwT2Jm1xc6ozvE/edit

**Comment by Keiven-Soto** [comment]
Acceptance criteria met: waiting for review
