### ISSUE TITLE
Create Users Table in Database and Review schema

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#63]
Create users table in the database, which has the following specifications:
1. Design the users table schema, considering fields such as user ID, name, email, password hash, profile picture URL, banner, status, and average ratings.
2. Ensure the fields in the table have appropriate data types and constraints.

Recommended Priority: 5
Recommended Difficulty: 2

**Comment by Keiven-Soto** [comment]
I can work on this
