### ISSUE TITLE
Enhancing Filtering Options in Browser Page Interface

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#85]
Overview:
The objective is to augment the browsing experience by introducing additional filtering options on the browser page interface. This expansion aims to empower users with more control over their product discovery process, allowing for refined searches based on various criteria such as date, price range, and product attributes.

Enhanced Explication:

Sort by Date (Newest to Oldest): Implementing this filter enables users to arrange products based on their release or upload date. By staying updated with the latest additions to the inventory, users can prioritize novelty and freshness in their browsing experience.

Price Range: Integrating a price range filter empowers users to set budget constraints and narrow down search results accordingly. This feature facilitates targeted browsing, ensuring that users are presented with products within their financial parameters.

Product Category: Segmenting products into distinct categories enhances navigation efficiency, enabling users to quickly locate items that match their specific interests or needs. By providing intuitive access to relevant product subsets, this filter streamlines the browsing experience.

Availability: Incorporating a filter to display only available products helps users focus on items that are currently in stock. By minimizing frustration associated with out-of-stock or backordered items, this filter enhances the relevance of search results and streamlines the purchasing process.

Enhanced Explication:

By implementing these additional filtering options, users can refine their browsing experience to align more closely with their preferences and requirements. The introduction of sorting by date and price range facilitates more targeted searches, while the inclusion of product categories enhances navigation efficiency. Additionally, filtering by availability ensures that users are presented with relevant options that are currently in stock. Overall, these enhancements contribute to a more user-centric browsing experience, improving satisfaction and facilitating smoother product discovery and selection.

Urgency: 5
Diffuculty: 2

**Comment by GaddPetrivoki** [comment]
Just added Sort by Date and sort by Price. Price Range is still having some issues. I tried to get the pricerange value and filtering the list by it but trying to get the state from panResponder is causing some problems.
