### ISSUE TITLE
Address Milestone 1 Feedback (2.2.1 Epics and User Stories)

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#94]
Adress the following feedback for the milestone 1 documentation:
Your epics are relatively close to the user stories. You can either make the epics more high-level or you can make the user stories more low-level.
Recommended Priority: 2
Recommended Difficulty: 5

**Comment by AngelGonzs** [comment]
The feedback has been addressed to more easily distinguish between the User Stories and Epics. Once reviewed, I believe this issue can be closed.
