### ISSUE TITLE
Address Milestone 1 Feedback (2.2.3 Domain Requirements)

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#96]
Adress the following feedback for the milestone 1 documentation:
1. "Must allow" does not make a requirement. Someone who just wants to avoid doing the work could just say "our system does nothing against the scheduling of appointments, so it allows scheduling of appointments: done".
2. Make domain requirements relevant to the project.

Recommended Priority: 5
Recommended Difficulty: 4

**Comment by GaddPetrivoki** [comment]
Started writing some comments on the documentation. Added some requirements that are more specific.
